// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlNMP5_Kn7bDuCNN2WeOkV_aE3uzocD-Y',
    appId: '1:462543252373:web:5b7127f69750da78f9649c',
    messagingSenderId: '462543252373',
    projectId: 'sociality-sessions-685f6',
    authDomain: 'sociality-sessions-685f6.firebaseapp.com',
    databaseURL: 'https://sociality-sessions-685f6-default-rtdb.firebaseio.com',
    storageBucket: 'sociality-sessions-685f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQnPvxFclaIG0sn_sdKk3dTj0bv1LF_wY',
    appId: '1:462543252373:android:23c5aa2c13f6122cf9649c',
    messagingSenderId: '462543252373',
    projectId: 'sociality-sessions-685f6',
    databaseURL: 'https://sociality-sessions-685f6-default-rtdb.firebaseio.com',
    storageBucket: 'sociality-sessions-685f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3hJiTTNeErgUc44Uz-9D6DsndUqnMva0',
    appId: '1:462543252373:ios:d6fe3fb109bcbb42f9649c',
    messagingSenderId: '462543252373',
    projectId: 'sociality-sessions-685f6',
    databaseURL: 'https://sociality-sessions-685f6-default-rtdb.firebaseio.com',
    storageBucket: 'sociality-sessions-685f6.firebasestorage.app',
    iosBundleId: 'com.example.socialitySessionTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3hJiTTNeErgUc44Uz-9D6DsndUqnMva0',
    appId: '1:462543252373:ios:d6fe3fb109bcbb42f9649c',
    messagingSenderId: '462543252373',
    projectId: 'sociality-sessions-685f6',
    databaseURL: 'https://sociality-sessions-685f6-default-rtdb.firebaseio.com',
    storageBucket: 'sociality-sessions-685f6.firebasestorage.app',
    iosBundleId: 'com.example.socialitySessionTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlNMP5_Kn7bDuCNN2WeOkV_aE3uzocD-Y',
    appId: '1:462543252373:web:a703662095859c63f9649c',
    messagingSenderId: '462543252373',
    projectId: 'sociality-sessions-685f6',
    authDomain: 'sociality-sessions-685f6.firebaseapp.com',
    databaseURL: 'https://sociality-sessions-685f6-default-rtdb.firebaseio.com',
    storageBucket: 'sociality-sessions-685f6.firebasestorage.app',
  );

}